import {chromium} from '@playwright/test';
import {readFile,writeFile} from 'node:fs/promises';
import {icon} from '../dist/app/ui/icons.js';
const svg=await readFile('public/icon.svg','utf8');
const mask=await readFile('public/icon-maskable.svg','utf8');
const names=[...((await readFile('src/ui/icons.ts','utf8')).matchAll(/^  (\w+):/gm))].map(m=>m[1]);
const nav=[['home','Home'],['vault','Vault'],['plus','Add'],['user','Profile'],['settings','Settings']];
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><title>Selected CareerProof branding</title><style>
*{box-sizing:border-box}body{margin:0;padding:40px;background:#f6f8fa;color:#142c40;font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}h1{margin:0 0 8px;font-size:32px;letter-spacing:-1px}.intro{color:#5b6c7c;margin:0 0 24px}.brand{background:white;border:1px solid #dce4ea;border-radius:16px;padding:28px;display:flex;gap:36px;align-items:center}.large svg{width:216px;height:216px;display:block}.samples{display:flex;gap:28px;align-items:center;flex:1}.sample{text-align:center;font-size:13px;color:#5b6c7c}.sample svg{display:block;width:72px;height:72px;margin:auto auto 12px}.sample.small svg{width:32px;height:32px}.wordmark{font-size:32px;font-weight:700;letter-spacing:-1px}.wordmark small{display:block;font-size:13px;font-weight:400;color:#5b6c7c;letter-spacing:1px}.nav{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;background:#fff;border:1px solid #dce4ea;border-radius:16px;padding:16px;max-width:700px}.nav>div{display:flex;align-items:center;flex-direction:column;justify-content:center;padding:8px;font-size:14px;color:#5b6c7c;font-weight:600;border-radius:12px;gap:4px}.nav .active{background:#e7f4f2;color:#176b73}.active .icon-fill{fill:currentColor}.nav-icon{width:44px;height:44px;display:grid;place-items:center}.add .nav-icon{background:#176b73;color:white;border-radius:50%}.nav .add{color:#176b73}h2{font-size:20px;margin:24px 0 12px}.family{display:flex;flex-wrap:wrap;gap:12px}.family>div{width:76px;text-align:center;font-size:11px;color:#5b6c7c}.family svg{display:block;margin:0 auto 6px;color:#142c40}footer{font-size:13px;color:#5b6c7c;margin-top:24px}</style><h1>CareerProof · Selected identity</h1><p class="intro">Concept 1 — Modern Monogram · Editable vector reconstruction of your selected reference</p><section class="brand"><div class="large">${svg}</div><div class="samples"><div class="sample">${mask}Maskable</div><div class="sample small">${svg}32 px</div><div class="wordmark">CareerProof<small>PERSONAL CAREER OS</small></div></div></section><h2>Five destinations. One icon family.</h2><section class="nav">${nav.map(([name,label],i)=>`<div class="${i===0?'active':i===2?'add':''}"><span class="nav-icon">${icon(name,28)}</span>${label}</div>`).join('')}</section><h2>Application icon family</h2><section class="family">${names.map(name=>`<div>${icon(name,24)}${name}</div>`).join('')}</section><footer>24 px coordinate system · 2 px rounded strokes · Navy / teal · PNG 192 / 512, maskable 512, Apple touch 180, favicon 16 / 32</footer></html>`;
await writeFile('docs/branding/selected-branding.html',html);
const browser=await chromium.launch();
try {const page=await browser.newPage({viewport:{width:1200,height:800}});await page.setContent(html);await page.screenshot({path:'docs/branding/selected-branding.png',fullPage:true});}finally{await browser.close();}
